### ISSUE TITLE
feat: Optional tools for team work

### ISSUE THREAD

**Issue by ObaidQatan** [t3-oss/create-t3-app#1267]
### Is your feature request related to a problem? Please describe.

The boilerplate is powerful, however when I work together with team members, we always wanted our favorite tools for checking and testing maybe. Integration of tools like jest, husky, ci, and branch-protection would be great.

### Describe the solution you'd like to see

Developers can definitely choose the libraries they prefer, however when working with a team, wouldn't it be better if we just stick into particular loved tools to ensure applying the same rules (as in frameworks) ?
Something like this:
```powershell
? Which packages would you like to enable? nextAuth, prisma, tailwind, trpc
? Would you like to integrate team tools? [Y\n] y
? Enable branch protection? [Y\n] y
> Enter protected branch name: dev
```
This will initialize:
-  `.husky` directory with `pre-commit` that applies linting and prettying for our code.
- Configuration for `jest`.
- `.github/workflows/main.yml` will be added with minimal jobs.
- For branch protection, github actions like [Branch Protection](https://github.com/marketplace/actions/branch-protection) can be used with minimal configuration of `.github/config/branch_protection.yml` as follows:
```yml
- branch: dev
  protection:
    required_status_checks:
      strict: true
      contexts:
        - lint
        - build
    required_pull_request_reviews:
      dismissal_restrictions: null
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
      required_approving_review_count: 1
    required_linear_history: false
    allow_force_pushes: false
    allow_deletions: false
```

### Describe alternate solutions

These tools can also be installed optionally, the same way prisma, nextAuth, trcp and tailwind are integrated:
```powershell
? Which packages would you like to enable? nextAuth, prisma, tailwind, trpc, husky, jest
```

### Additional information

Similar case I have seen, initially Prettier was not configured by default, some people may even prefer other alternatives. However, in team work, differences in code prettying rules may result to problems like meaningless conflicts when merging PR, or difficulty in debugging other members code.
